version: '3'

services:
  santoryu-backend:
    container_name: santoryu-backend-app
    image: 497217256558.dkr.ecr.ap-northeast-1.amazonaws.com/santoryu-backend-prod:latest
    networks:
      - santoryu-backend-network
    environment:
      - ENV=local
      - TZ=Asia/Seoul

  proxy:
    container_name: santoryu-nginx
    image: 497217256558.dkr.ecr.ap-northeast-1.amazonaws.com/santoryu-nginx-prod:latest
    restart: always
    networks:
      - santoryu-backend-network
    ports:
      - "80"

networks:
  santoryu-backend-network: