version: '3'

services:
  santoryu-backend:
    container_name: santoryu-backend-app
    image: 497217256558.dkr.ecr.ap-northeast-1.amazonaws.com/santoryu-backend-prod:latest
    networks:
      - santoryu-backend-network

  proxy:
    container_name: santoryu-nginx
    image: 497217256558.dkr.ecr.ap-northeast-1.amazonaws.com/santoryu-nginx-prod:latest
    restart: always
    networks:
      - santoryu-backend-network
    ports:
      - "80"

  santoryu-mongo:
    container_name: santoryu-mongo
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"

networks:
  santoryu-backend-network: